### ISSUE TITLE
Improve: UI of the website

### ISSUE THREAD

**Issue by icoderharshit** [FayasNoushad/Website#66]
Hey there, I just saw your website and it's cool. I wanted to make the UI a bit better, and also as your repository has label Hacktoberfest I want to make my first PR for this issue. Kindly assign me this issue @FayasNoushad

**Comment by FayasNoushad** [comment]
You can make your pull request

**Comment by icoderharshit** [comment]
Ok, surely. I am creating a PR for the same soon. Looking forward to doing contributions in this repository. Thank you :) @FayasNoushad

**Comment by FayasNoushad** [comment]
Welcome
